---

- name: Reboot Host
  become: true
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible
    # INFO increased from 60 due to windows env rebooting ubuntu too slow
    reboot_timeout: 180

...
